openapi: 3.0.0
info:
  title: Simple Inventory API
  description: This is a simple API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0-oas3
servers:
- url: https://virtserver.swaggerhub.com/tutorial/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /student/{student_id}:
    get:
      summary: gets student
      description: |
        Returns a single student
      operationId: get_student_by_id
      parameters:
      - name: student_id
        in: path
        description: the uid
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        "400":
          description: invalid ID
        "404":
          description: not found
      x-openapi-router-controller: swagger_server.controllers.default_controller
    delete:
      summary: gets student
      description: |
        delete a single student
      operationId: delete_student
      parameters:
      - name: student_id
        in: path
        description: the uid
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: successful operation
        "400":
          description: invalid ID
        "404":
          description: not found
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /student:
    post:
      summary: Add a new student
      description: Adds an item to the system
      operationId: add_student
      requestBody:
        description: Student item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        "200":
          description: created
          content:
            application/json:
              schema:
                type: integer
                format: int32
                x-content-type: application/json
        "400":
          description: "invalid input, object invalid"
        "409":
          description: an existing already exists
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Student:
      required:
      - first_name
      - last_name
      type: object
      properties:
        student_id:
          type: integer
          format: int32
          example: 12345678
        first_name:
          type: string
          example: John
        last_name:
          type: string
          example: Doe
        gradeRecord:
          type: array
          items:
            $ref: '#/components/schemas/GradeRecord'
      example:
        gradeRecord:
        - grade: 8.3
          subject_name: DevOps and Cloud Engineering
        - grade: 8.3
          subject_name: DevOps and Cloud Engineering
        student_id: 12345678
        last_name: Doe
        first_name: John
    GradeRecord:
      required:
      - grade
      - subject_name
      type: object
      properties:
        subject_name:
          type: string
          example: DevOps and Cloud Engineering
        grade:
          maximum: 10
          minimum: 0
          type: number
          format: float
          example: 8.3
      example:
        grade: 8.3
        subject_name: DevOps and Cloud Engineering
  responses:
    "400":
      description: invalid ID
    "404":
      description: not found

